name: CI
on: push

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Set up Python with Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          python3 -m venv ~/.venv
          source ~/.venv/bin/activate
          poetry install
        shell: bash

      - name: Run Unit Tests
        run: |
          source ~/.venv/bin/activate
          poetry run pytest -v tests
        shell: bash

      - uses: chartboost/ruff-action@v1
        with:
            args: --check .
            fix_args: --fix .
            config: .ruff.toml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: 'style fixes by ruff'
