  name: ci

  on:
    pull_request:
      branches: [ master ]

  jobs:
    ci:
      runs-on: ubuntu-latest

      services:
        postgres:
          image: postgres
          env:
            POSTGRES_USER: python-problems-bot
            POSTGRES_PASSWORD: python-problems-bot
            POSTGRES_DB: python-problems-bot
          ports:
            - 5436:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Install poetry
          uses: snok/install-poetry@v1

        - name: Install dependencies
          working-directory: ./backend
          run: poetry install --no-interaction --no-root

        - name: Install golang-migrate
          working-directory: ./backend
          run: |
            curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz;
            sudo mv migrate /usr/bin/migrate;
            which migrate

        - name: Run migrations
          working-directory: ./backend
          run: migrate -path ./migrations -database "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:$POSTGRES_PORT/$POSTGRES_DB?sslmode=disable" --verbose up
          env:
            POSTGRES_USER: python-problems-bot
            POSTGRES_PASSWORD: python-problems-bot
            POSTGRES_PORT: 5436
            POSTGRES_DB: python-problems-bot

        - name: Run linter
          working-directory: ./backend
          run: poetry run ruff check .

        - name: Run unit tests
          working-directory: ./backend
          run: poetry run pytest -v tests
          env:
            TOKEN: token
            PAYMENT_PROVIDER_TOKEN: token
            WEB_APP_URL: web-app-url.com

        - name: Run functional tests
          working-directory: ./backend
          run: poetry run pytest -v tests_functional
          env:
            PG_USER: python-problems-bot
            PG_PASSWORD: python-problems-bot
            PG_PORT: 5436
            PG_DB: python-problems-bot
            TOKEN: token
            PAYMENT_PROVIDER_TOKEN: token
            WEB_APP_URL: web-app-url.com
